exclude: ['README.md', 'preview.sh', 'Gemfile', 'Gemfile.lock']

# Used to generate the site
title: "What are we doing dnd podcast"
title_short: "SomeDiceGuys DND"
email: "somediceguysdnd@gmail.com"
description: "DND podcast app"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://somediceguysdnd.com" # the base hostname & protocol for your site
itunes_url: "https://podcasts.apple.com/us/podcast/what-are-we-even-doing-a-dnd-podcast/id1528198962?uo=4"

# itunes_id creates a smart banner on Safari in iOS prompting
# visitors to subscribe
# Uncomment next line to enable
#itunes_id: xxx # The ID is after the last slash in itunes_url above minus the letters "id"
twitter_username: @somediceguysdnd
#twitter_podcastname:

# For the SEO tag
#seo:
#  name: "Example Pod"
#  type: "CreativeWork"
#  about: "Brief description of your podcast."
#  person: "Your Name"

# Used to generate the iTunes-compatible RSS feed
podcast:
  owner:
    name: SomeDiceGuys
    email: somediceguysdnd@gmail.com
  explicit: "yes" # Change to yes if you're a potty mouth
  image: /img/diceguys-2000.png # iTunes requires 2,000 pixel art
  keywords: "gaming"
  categories:
    - category: "podcast"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-seo-tag
