# Site settings
title: "SomeDiceGuys DND"
description: "A Homebrewed DND podcast"
podcast-description: "What are we even doing | A DnD Podcast"
url:  "https://somediceguysdnd.com/" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "1019 Studios"
  email: "1019studiosteam@gmail.com"
  url: "https://somediceguysdnd.com/"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 8
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: somediceguys
  card: summary
facebook:
  app_id:
logo: /assets/img/DND_Podcast_Cover.png
social:
  name: 1019 Studios
  links:
    - https://github.com/somediceguys/
    - https://twitter.com/somediceguys
lang: it

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: SomeDiceGuys Podcast
podcast_author: 1019 Studios
podcast_email: 1019studiosteam@gmail.com
podcast_subtitle: "A DnD Podcast"
podcast_summary: "What are we even doing | A Dungeons and Dragons Podcast"
podcast_description: "What are we even doing | A Dungeons and Dragons Podcast"
podcast_explicit: "yes"
podcast_type: serial
podcast_lang: en
podcast_launch: "2020-08-08" #Launch date of your podcast
podcast_copyright: "&#xA9;1019 Studios"
podcast_feed: https://anchor.fm/s/30f31760/podcast/rss
podcast_artwork: "/assets/img/DND_Podcast_Cover.png"
